### ISSUE TITLE
Add post test log retrieval functionality

### ISSUE THREAD

**Issue by prashantmital** [mongodb-labs/drivers-atlas-testing#4]
After a test case has been run, `astrolabe` should:

- wait until Atlas logs are current (i.e logs from the period of time during which tests were run are available via the API),
- download the mongod/mongos logs in an appropriately named folder hierarchy that makes it easy to find logs corresponding to specific tests,
- create a zip archive/tarball containing all the logs.

**Comment by prashantmital** [comment]
Log collection should ideally be performed in a different process to avoid blocking the progression of the test-suite. Waiting for several minutes while the logs catch up would prevent the execution of the next test and result in even longer test run times.

**Comment by p-mongo** [comment]
@prashantmital This was done as part of DRIVERS-828.
