### ISSUE TITLE
Use non-dotted directories for workload executors

### ISSUE THREAD

**Issue by p-mongo** [mongodb-labs/drivers-atlas-testing#53]
Currently workload executors are located in subdirectories of `.evergreen`. In Unix the leading dot makes a file hidden, which means:

- Commands like `ls` do not show these files/directories by default
- Shell completion by default does not show them

Also, the leading dot is awkward to type. I use Dvorak layout but even on qwerty "a" is on the home row and "." is one row down. On Dvorak . and e are adjacent (same finger) and are arranged vertically.

Is it possible to have the workload executors be under a path that does not contain  dotted directories please?

**Comment by prashantmital** [comment]
@ShaneHarvey suggested we could move the workloads to a `workloads` directory in the project root.

**Comment by p-mongo** [comment]
:+1:  works for me.

**Comment by prashantmital** [comment]
Closed in #59
